import './globals.css'
import { Providers } from '@/components/provider/Providers';


export const metadata = {
  title: 'Real time chat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  )
}
